import Hydrate from "./components/Hydrate";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Hydrate>
        <body>
          <Toaster
            position="top-center"
            toastOptions={{
              duration: 1500,
            }}
          />
          {children}
        </body>
      </Hydrate>
    </html>
  );
}
